---
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

accesslog: {}

api:
  dashboard: true
  insecure: true

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

# -- Configure your CertificateResolver here...
certificatesResolvers:
  cloudflare:
    acme:
      email: "<CLOUDFLARE_EMAIL>"
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# --> (Optional) Disable TLS Cert verification check
serversTransport:
  insecureSkipVerify: true
# <--

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  #file:
  #  filename: /etc/traefik/dynamic_conf.yml