services:
  traefik:
    image: docker.io/library/traefik:v3.2.3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      #- 8080:8080 # Traefik dashboard
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./data/certs/:/var/traefik/certs/:rw
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      #- ./config/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true